// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVCvAZYtmhhqS5RIK2wVmlr0-XO11jiU',
    appId: '1:919456786265:web:da79492552616d36f58e48',
    messagingSenderId: '919456786265',
    projectId: 'clubfrance-login-app',
    authDomain: 'clubfrance-login-app.firebaseapp.com',
    storageBucket: 'clubfrance-login-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgb5_R1EYCNPDZrvtaO_rJXecxrxj5L4',
    appId: '1:919456786265:android:604d9622a6d0fbc0f58e48',
    messagingSenderId: '919456786265',
    projectId: 'clubfrance-login-app',
    storageBucket: 'clubfrance-login-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgcZUGVxkNnOxiXL8mikQICMb6V1aBho',
    appId: '1:919456786265:ios:26dc7a5fe44792c2f58e48',
    messagingSenderId: '919456786265',
    projectId: 'clubfrance-login-app',
    storageBucket: 'clubfrance-login-app.firebasestorage.app',
    iosBundleId: 'mx.org.clubfrance.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgcZUGVxkNnOxiXL8mikQICMb6V1aBho',
    appId: '1:919456786265:ios:c1308598d2eee313f58e48',
    messagingSenderId: '919456786265',
    projectId: 'clubfrance-login-app',
    storageBucket: 'clubfrance-login-app.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeVCvAZYtmhhqS5RIK2wVmlr0-XO11jiU',
    appId: '1:919456786265:web:8fee3d36a69f7ce8f58e48',
    messagingSenderId: '919456786265',
    projectId: 'clubfrance-login-app',
    authDomain: 'clubfrance-login-app.firebaseapp.com',
    storageBucket: 'clubfrance-login-app.firebasestorage.app',
  );
}
