# ios/Podfile - Versión ultra simple
platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end